[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  HUGO_EXTENDED = "true"
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


