[build]
  command = "hugo"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


